<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-24T01:59:19 IST" name="Default suite" finished-at="2022-08-24T01:59:27 IST" duration-ms="7824">
    <groups>
    </groups>
    <test started-at="2022-08-24T01:59:19 IST" name="Default test" finished-at="2022-08-24T01:59:27 IST" duration-ms="7824">
      <class name="test.logintest">
        <test-method is-config="true" signature="lauchbroweser()[pri:0, instance:test.logintest@3059cbc]" started-at="2022-08-24T01:59:19 IST" name="lauchbroweser" finished-at="2022-08-24T01:59:24 IST" duration-ms="4444" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lauchbroweser -->
        <test-method is-config="true" signature="pageobjects()[pri:0, instance:test.logintest@3059cbc]" started-at="2022-08-24T01:59:24 IST" name="pageobjects" finished-at="2022-08-24T01:59:24 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pageobjects -->
        <test-method signature="verifyurlpage()[pri:-1, instance:test.logintest@3059cbc]" started-at="2022-08-24T01:59:24 IST" name="verifyurlpage" finished-at="2022-08-24T01:59:24 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyurlpage -->
        <test-method signature="logintest()[pri:0, instance:test.logintest@3059cbc]" started-at="2022-08-24T01:59:24 IST" name="logintest" finished-at="2022-08-24T01:59:27 IST" duration-ms="3210" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method signature="verifyloginpage()[pri:0, instance:test.logintest@3059cbc]" started-at="2022-08-24T01:59:27 IST" name="verifyloginpage" finished-at="2022-08-24T01:59:27 IST" duration-ms="23" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ Login ] but found [Search]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ Login ] but found [Search]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at test.logintest.verifyloginpage(logintest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginpage -->
        <test-method is-config="true" signature="teardownEnviornment()[pri:0, instance:test.logintest@3059cbc]" started-at="2022-08-24T01:59:27 IST" name="teardownEnviornment" finished-at="2022-08-24T01:59:27 IST" duration-ms="95" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardownEnviornment -->
      </class> <!-- test.logintest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
